apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: infra
  labels:
    app: redis-exporter
spec:
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:   
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: aicloud
                operator: In
                values:
                - "true"   
      serviceAccountName: "default"
      containers:
      - name: exporter
        image: docker.io/oliver006/redis_exporter:v0.31.0
        imagePullPolicy: "IfNotPresent"
        args:
        env:
        - name: REDIS_ADDR
          value: "redis-master:6379,redis-slave:6379"
        - name: REDIS_ALIAS
          value: redis
        - name: REDIS_PASSWORD
          value: admin
        volumeMounts:
        ports:
        - name: exporter
          containerPort: 9121
        resources:
          null


