apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    app: redis-exporter
    k8s-app: redis-exporter
spec:
  endpoints:
  - interval: 10s
    honorLabels: true
    port: exporter
    path: /metrics
    scheme: http
  jobLabel: "redis-exporter"
  selector:
    matchLabels:
      app: redis-exporter
  namespaceSelector:
    matchNames:
      - infra



