apiVersion: v1
kind: Service
metadata:
  name: redis-metrics
  namespace: infra
  labels:
    app: redis-metrics    
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9121
    targetPort: metrics
  selector:
    app: redis
    release: redis
    role: metrics
---
# Source: redis/templates/redis-master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: infra
  labels:
    app: redis-master
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: redis
    release: "redis"
    role: master

# ---
# # Source: redis/templates/redis-master-svc.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: redis-master-external
#   namespace: infra
#   labels:
#     app: redis-master
# spec:
#   type: ClusterIP
#   ports:
#   - name: redis
#     port: 6379
#     targetPort: redis
#   selector:
#     app: redis
#     release: "redis"
#     role: master
#   externalIPs:
#     - 9.4.22.10
---
# Source: redis/templates/redis-slave-svc.yaml

# apiVersion: v1
# kind: Service
# metadata:
#   name: redis-slave
#   namespace: infra
#   labels:
#     app: redis-slave
# spec:
#   type: ClusterIP
#   ports:
#   - name: redis
#     port: 6379
#     targetPort: redis
#   selector:
#     app: redis
#     release: "redis"
#     role: slave

