## 通过vs代理访问其他的服务，包括pipline,argp,minio,grafana等
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: infra-kubeflow-dashboard
#  namespace: infra
#spec:
#  gateways:
#  - kubeflow/kubeflow-gateway
#  hosts:
#  - "*"    # 管理平台的域名   kubeflow.local.com
#  http:
#  - route:
#    - destination:
#        host: kubeflow-dashboard.infra.svc.cluster.local
#        port:
#          number: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kube-system-k8s-dashboard-cluster
  namespace: kube-system
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - "*"   # 配置自己管理的域名kubeflow.local.com
  http:
  - match:
    - uri:
        prefix: /k8s/dashboard/cluster/
    rewrite:
      uri: /
    route:
    - destination:
        host: kubernetes-dashboard-cluster.kube-system.svc.cluster.local
        port:
          number: 9090

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: monitoring-grafana
  namespace: monitoring
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - "*"  # 配置自己管理的域名 kubeflow.local.com
  http:
  - match:
    - uri:
        prefix: /grafana/
    rewrite:
      uri: /
    route:
    - destination:
        host: grafana.monitoring.svc.cluster.local
        port:
          number: 8080