apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        # 自定义host
        hosts {
          1.1.1.1    example1.local.com
          2.2.2.2    example2.local.com
          172.16.247.0 pypi.tuna.tsinghua.edu.cn
          fallthrough
        }
        prometheus :9153
        forward . "/etc/resolv.conf"
        cache 30
        loop
        reload
        loadbalance
    }
    # oa.com结尾的域名使用此类dns代理
    oa.com:53 {
      errors
      cache 30
      hosts {
        3.3.3.3    example3.oa.com
        4.4.4.4    example4.oa.com
        fallthrough
      }
      forward . 4.4.4.4 5.5.5.5
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system

