apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  image: quay.io/prometheus/prometheus:v2.27.1
  replicas: 1
  retention: 3d
  resources:
    requests:
      memory: 400Mi
#  storage:
#    volumeClaimTemplate:
#      spec:
#        accessModes:
#        - ReadWriteOnce
#        resources:
#          requests:
#            storage: 10Gi
#        selector:
#          matchLabels:
#            monitoring-pvname: monitoring-prometheus-pv
#      status: {}
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
#  version: v2.3.1

  additionalScrapeConfigs:
    name: prometheus-config
    key: prometheus-additional.yaml